sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker

before install:
  - docker build -t shangarab123/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true shangarab123/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-react
  env: DockerReact-env