sudo: required
services:
  - docker

before install:
  - docker build -t saonmustafi/docker-react -f Dockerfile.dev .

language: node_js

scripts:
  - docker run saonmustafi/docker-react npm test -- --coverage