sudo: required
language: node_js
services:
  - docker

before install:
  - echo Starting build
  - docker build -t shangarab123/docker-react -f Dockerfile.dev .
  - echo bhuild has been completed

scripts:
  - docker run shangarab123/docker-react npm test -- --coverage