sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker

before install:
  - docker build -t shangarab123/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true shangarab123/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-138331444497"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"