sudo: required
language: node_js
services:
  - docker

before install:
  - docker build -t shangarab123/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true shangarab123/docker-react npm run test

